version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - QUEUE_CONNECTION=database
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - LOG_CHANNEL=single
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    depends_on:
      - redis
    networks:
      - playlist-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - playlist-network

  # Optional: Queue worker for background jobs
  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan queue:work --tries=3 --timeout=90
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - QUEUE_CONNECTION=database
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    depends_on:
      - app
      - redis
    networks:
      - playlist-network

volumes:
  redis_data:

networks:
  playlist-network:
    driver: bridge
