services:
  - type: web
    name: playlist-converter
    runtime: docker
    buildCommand: "docker build -t playlist-converter ."
    startCommand: "docker run -p $PORT:80 playlist-converter"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: single
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: APP_URL
        value: https://your-app-name.onrender.com
